language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run deploy-storybook -- --ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
branch: master